
            <div id="login-template">
                <header id="special-header">
                  <nav class="navbar navbar-expand-lg">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="signup.php">Aun no tienes una cuenta?</a>
                            </li>
                        </ul>
                    </div>
                  </nav>
                </header>