                <footer id="normal-footer">
                  <nav class="navbar navbar-expand-lg">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav mr-auto">
                          <li class="nav-item active">
                            <a class="nav-link" href="index.php">Vestimenta</a>
                          </li>
                          <li class="nav-item active">
                            <a class="nav-link" href="about-us.php">Sobre nosotros</a>
                          </li>
                          <li class="nav-item active">
                            <a class="nav-link" href="contact-us.php">Contactanos</a>
                          </li>
                          <li class="nav-item active">
                            <a class="nav-link" href="faq.php">FAQ</a>
                          </li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="#"><i class="fab fa-facebook-f"></i></a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="#"><i class="fab fa-twitter"></i></a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="#"><i class="fab fa-instagram"></i></a>
                            </li>
                        </ul>
                    </div>
                </nav>
                </footer>
            </div>
            <?= View::partial('commons/scriptsfooter') ?>
        </body>
</html>