<!DOCTYPE html> 
<html lang="es">
        <head>
            <meta charset="UTF-8">
            <meta name="Vestimenta" content="Tienda de ropa en linea">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
           
            <?= View::partial('commons/metainfoheader') ?>

           
            <meta http-equiv="Expires" content="0">
            <meta http-equiv="Last-Modified" content="0">
            <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
            <meta http-equiv="Pragma" content="no-cache">
        </head>
        <body>
            <div id="login-template">
                <header id="special-header">
                  <nav class="navbar navbar-expand-lg">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="signup.php">Aun no tienes una cuenta?</a>
                            </li>
                        </ul>
                    </div>
                  </nav>
                </header>