<?= View::partial('layout/special-headerL'); ?>

<div id="info-square">
    <h1>Ya eres parte del club?</h1>
    <p>Ingresa los datos de tu cuenta para acceder a la comunidad y obtener las prendas del momento.</p>
</div>
<div id="form-square">
    <div class="container bgLogInForm" id="login-form">

        <?= Html::img('logoB.png', '', "id = 'logo-login' ") ?>

        <form action="login.php" method="post">
            <div class="form-inline">
                <i class="fas fa-user"></i>
                <input type="text" name="usuario" class="form-control" placeholder="Usuario">
            </div>
            <div class="form-inline">
                <i class="fas fa-key"></i>
                <input type="password" name="password" class="form-control" placeholder="Contraseña">
            </div>
            <button type="submit" class="btn btn-principal">Ingresar</button>
        </form>
    </div>
</div>


<?= View::partial('layout/special-footer');