

<div id="info-square">
    <h1>Bienvenido</h1>
    <p>Llena los campos para obtener tu cuenta y ser parte de la comunidad de moda mas grande de Mexico</p>
</div>
<div id="form-square">
    <div class="container bgLogInForm" id="login-form">

        <?= Html::img('logoB.png', '', "id = 'logo-register' ") ?>

        <form action="signup.php" method="post">
            <div class="form-inline">
                <i class="fas fa-user"></i>
                <input type="text" name="usuario" class="form-control" placeholder="Usuario">
            </div>
            <div class="form-inline">
                <i class="fas fa-key"></i>
                <input type="password" name="password" class="form-control" placeholder="Contraseña">
            </div>
            <div class="form-inline">
                <i class="fas fa-key"></i>
                <input type="password" name="password_confirm" class="form-control" placeholder="Confirma contraseña">
            </div>
            <button type="submit" class="btn btn-principal">Registrar</button>
        </form>
    </div>
</div>
